name: Github Actions
on: push
jobs:
   test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: pnpm i
      - name: Test
        run: pnpm test
